CREATE TABLE SONGS(
    ID      INTEGER PRIMARY KEY,
    NAME    TEXT                NOT NULL
);

CREATE TABLE ARTISTS(
    ID      INTEGER PRIMARY KEY,
    NAME    TEXT                NOT NULL
);

CREATE TABLE PLAYDATES(
    ID      INTEGER PRIMARY KEY,
    DATE    TEXT                NOT NULL,
    SONGID  INTEGER             NOT NULL,
    FOREIGN KEY(SONGID) REFERENCES SONGS(ID)
);

CREATE TABLE SONGARTIST(
    SONGID      INTEGER NOT NULL,
    ARTISTID    INTEGER NOT NULL,
    FOREIGN KEY(SONGID) REFERENCES SONGS(ID),
    FOREIGN KEY(ARTISTID) REFERENCES ARTISTS(ID)
);