CREATE TABLE ARTISTS(
    ARTIST_ID      INTEGER PRIMARY KEY,
    ARTIST_NAME    TEXT                NOT NULL
);

CREATE TABLE SONGS(
    SONG_ID      INTEGER PRIMARY KEY,
    SONG_NAME    TEXT                NOT NULL,
    ARTIST_ID    INTEGER             NOT NULL,
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ARTIST_ID)
);

CREATE TABLE PLAYDATES(
    DATETIME     TEXT                NOT NULL,
    SONG_ID      INTEGER             NOT NULL,
    FOREIGN KEY(SONG_ID) REFERENCES SONGS(SONG_ID)
);
